const ADD_TODO = 'ADD_TODO';
const SET_EDIT = 'SET_EDIT';
const SET_TODO = 'SET_TODO';
const EDIT_TODO = 'EDIT_TODO';
const SHOW_MODAL = 'SHOW_MODAL';
const HIDE_MODAL = 'HIDE_MODAL';
const DELETE_TODO = 'DELETE_TODO';
const SET_FILTERS = 'SET_FILTERS';
const SET_SPINNER = 'SET_SPINNER';
const SET_COMPLETED = 'SET_COMPLETED';
const FETCH_TODO_LIST_REQUEST = 'FETCH_TODO_LIST_REQUEST';
const FETCH_TODO_LIST_SUCCESS = 'FETCH_TODO_LIST_SUCCESS';
const FETCH_TODO_LIST_FAILURE = 'FETCH_TODO_LIST_FAILURE';

export {
  ADD_TODO,
  SET_EDIT,
  SET_TODO,
  EDIT_TODO,
  SHOW_MODAL,
  HIDE_MODAL,
  DELETE_TODO,
  SET_FILTERS,
  SET_SPINNER,
  SET_COMPLETED,
  FETCH_TODO_LIST_REQUEST,
  FETCH_TODO_LIST_SUCCESS,
  FETCH_TODO_LIST_FAILURE,
}
